"""Handshake transaction vectors generated by HSD and stored in hns-node-rs.

Source: fixtures/hsd/transactions/codec-v1.json at
handshake-rs/hns-node-rs c0785719db68a574a13fba224af5ff34ead13c3e.
"""

import unittest

from basicswap.interface.hns.transaction import HnsTransaction, HnsTransactionError

RAW = (
    "01000000010808080808080808080808080808080808080808080808080808080808080808"
    "02000000feffffff012a0000000000000000140909090909090909090909090909090909"
    "090909020103616263630000000203010203020405"
)
TXID = "420f91c753c7ad480b3359f47ccbcab9e058a59d15fcd5e10bec66e04a55f274"
WITNESS_HASH = "fba6fa32ac4b157d754c951d98d1e6e5e13c8d705a72621cd944e835597980a2"


class HnsTransactionTest(unittest.TestCase):
    def test_hsd_codec_vector(self):
        raw = bytes.fromhex(RAW)
        tx = HnsTransaction.decode(raw)
        self.assertEqual(tx.encode(), raw)
        self.assertEqual(len(tx.base_encode()), 86)
        self.assertEqual(len(raw), 94)
        self.assertEqual(tx.txid(), TXID)
        self.assertEqual(tx.witness_hash(), WITNESS_HASH)
        self.assertEqual(tx.outputs[0].covenant.kind, 2)

    def test_witness_changes_witness_hash_but_not_txid(self):
        from dataclasses import replace

        tx = HnsTransaction.decode(bytes.fromhex(RAW))
        changed_input = replace(tx.inputs[0], witness=(b"different",))
        changed = replace(tx, inputs=(changed_input,))
        self.assertEqual(changed.txid(), tx.txid())
        self.assertNotEqual(changed.witness_hash(), tx.witness_hash())

    def test_noncanonical_or_trailing_bytes_rejected(self):
        raw = bytes.fromhex(RAW)
        with self.assertRaises(HnsTransactionError):
            HnsTransaction.decode(raw + b"\x00")
        with self.assertRaises(HnsTransactionError):
            HnsTransaction.decode(raw[:-1])
        with self.assertRaises(HnsTransactionError):
            HnsTransaction.decode(raw[:4] + b"\xfd\x01\x00" + raw[5:])


if __name__ == "__main__":
    unittest.main()
