# -*- coding: utf-8 -*-

# Copyright (c) 2024 tecnovert
# Distributed under the MIT software license, see the accompanying
# file LICENSE or http://www.opensource.org/licenses/mit-license.php.


OP_TXINPUTCOUNT = 0xc3
OP_1 = 0x51
OP_NUMEQUALVERIFY = 0x9d
OP_TXOUTPUTCOUNT = 0xc4
OP_0 = 0x00
OP_UTXOVALUE = 0xc6
OP_OUTPUTVALUE = 0xcc
OP_SUB = 0x94
OP_UTXOTOKENCATEGORY = 0xce
OP_OUTPUTTOKENCATEGORY = 0xd1
OP_EQUALVERIFY = 0x88
OP_UTXOTOKENCOMMITMENT = 0xcf
OP_OUTPUTTOKENCOMMITMENT = 0xd2
OP_UTXOTOKENAMOUNT = 0xd0
OP_OUTPUTTOKENAMOUNT = 0xd3
OP_INPUTSEQUENCENUMBER = 0xcb
OP_NOTIF = 0x64
OP_OUTPUTBYTECODE = 0xcd
OP_OVER = 0x78
OP_CHECKDATASIG = 0xba
OP_CHECKDATASIGVERIFY = 0xbb
OP_ELSE = 0x67
OP_CHECKSEQUENCEVERIFY = 0xb2
OP_DROP = 0x75
OP_EQUAL = 0x87
OP_ENDIF = 0x68
OP_HASH256 = 0xaa
OP_PUSHBYTES_32 = 0x20
OP_DUP = 0x76
OP_HASH160 = 0xa9
OP_CHECKSIG = 0xac
OP_SHA256 = 0xa8
OP_VERIFY = 0x69