    pivx_core:
        image: i_pivx
        build:
            context: pivx
            dockerfile: Dockerfile
        container_name: pivx_core
        volumes:
            - ${DATA_PATH}/pivx:/data
        expose:
            - ${PIVX_RPC_PORT}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
