    wownero_daemon:
        image: i_wownero_daemon
        build:
            context: wownero_daemon
            dockerfile: Dockerfile
        container_name: wownero_daemon
        volumes:
            - ${DATA_PATH}/wownero_daemon:/data
        expose:
            - ${BASE_WOW_RPC_PORT}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
